# The URL the site will be built for
base_url = "https://www.cblanken.dev"
title = "cblanken"
compile_sass = true
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]
build_search_index = true
theme = "terminimal-custom"
default_language = "en"
taxonomies = [
    {name = "tags", paginate_by = 10},
]

[markdown]
highlight_code = true
highlight_theme = "kronuz"
extra_syntaxes_and_themes = [ 
    "syntaxes/",
    "syntaxes/http/"
]

[extra]
enable_post_view_navigation = true
post_view_navigation_prompt = "Read more"
logo_text = "cblanken.dev"
accent_color = "orange"

menu_items = [
    {name = "About me", url = "$BASE_URL/about"},
    {name = "Blog", url = "$BASE_URL/blog"},
    {name = "Journal", url = "$BASE_URL/journal"},
    {name = "Projects", url = "$BASE_URL/projects"},
    {name = "Archive", url = "$BASE_URL/archive"},
    {name = "Tags", url = "$BASE_URL/tags"},
    {name = "RSS", url = "$BASE_URL/feeds"},
    {name = "github", url = "https://github.com/cblanken", newtab = true},
]

favicon = "/favicon.svg"
favicon_mimetype = "image/svg"

author = "Cameron Blankenbuehler"

